### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by wjl520** [trinanjan12/Image-Based-Virtual-Try-on-Network-from-Unpaired-Data#1]
Thanks for sharing the charming work. 
It is convenient to tell me that how to construct the dataset step by step for training. 
Thanks again.

**Comment by trinanjan12** [comment]
Hey, I am planning to share a detailed redme file within a month describing the procedure and other important things.

**Comment by wjl520** [comment]
@trinanjan12 
 I very much look forward, ah.

**Comment by armheb** [comment]
Hi, Thanks for sharing your awesome work, also looking forward to it! thanks

**Comment by trinanjan12** [comment]
@armheb not sure if I'll get time for a while. will try updating if I am free some time.

**Comment by armheb** [comment]
Thanks I'll appreciate it. I don't want to take your time for a detailed readme if you could guide me in the direction of how to train the model I'd be grateful.

**Comment by weij0626** [comment]
It's a great work ! Also looking forward to it !

**Comment by armheb** [comment]
Hi @trinanjan12, any update on the guide? I'd really appreciate it.
